apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-credit-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.1"
  POD_NAME: "go-credit"
  PORT: "5001"
  DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  NO_AZ: "true"
  #SERVER_URL_DOMAIN: "http://svc-go-account.test-a.svc.cluster.local:5000"
  #SERVER_URL_DOMAIN: "https://go-account.architecture.caradhras.io"
  SERVER_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv"
  X_APIGW_API_ID: "129t4y8eoj"
  TLS: "false"
