apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-credit-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "2.1"
  POD_NAME: "go-credit.k8"
  PORT: "5001"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  TLS: "false"    
  SETPOD_AZ: "false"
 
  SERVICE_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv" # call inside the cluster
  X_APIGW_API_ID: "129t4y8eoj"
  SERVICE_URL_DOMAIN_CB: "https://go-fund-transfer.architecture.caradhras.io"
  X_APIGW_API_ID_CB: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-xray-collector.default.svc.cluster.local:4317"
  ENV: "dev"
 #SERVER_URL_DOMAIN: "http://svc-go-account.test-a.svc.cluster.local:5000"
  #SERVER_URL_DOMAIN: "https://go-account.architecture.caradhras.io"