apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-credit-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.0"
  POD_NAME: "go-credit"
  PORT: "5001"
  DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  NO_AZ: "true"
