apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-credit-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "3.0"
  POD_NAME: "go-credit.k8"
  PORT: "5001"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  TLS: "false"    
  SETPOD_AZ: "false"
  ENV: "dev"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-xray-collector.default.svc.cluster.local:4317"

  NAME_SERVICE_01: "go-account"
  URL_SERVICE_01: "https://vpce.global.dev.caradhras.io/pv/get" # call inside the cluster
  METHOD_SERVICE_01: "GET"
  X_APIGW_API_ID_SERVICE_01: "129t4y8eoj"

  NAME_SERVICE_02: "go-account"
  URL_SERVICE_02: "https://vpce.global.dev.caradhras.io/pv/add/accountBalance" # call inside the cluster
  METHOD_SERVICE_02: "POST"
  X_APIGW_API_ID_SERVICE_02: "129t4y8eoj"

  NAME_SERVICE_03: "go-fund-transfer"
  URL_SERVICE_03: "https://vpce.global.dev.caradhras.io/pv/creditTransferEvent" # call inside the cluster
  METHOD_SERVICE_03: "POST"
  X_APIGW_API_ID_SERVICE_03: "unb2n5wala"

  #SERVER_URL_DOMAIN: "http://svc-go-account.test-a.svc.cluster.local:5000"
  #SERVER_URL_DOMAIN: "https://go-account.architecture.caradhras.io"